### ISSUE TITLE
Issue With this Release

### ISSUE THREAD

**Issue by Invisiblearound** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#1]
Not Working, I also have same config its not working ,

I have attached my working config but its no internet can u solve it.
I tried many 
[EFI.zip](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/files/5977005/EFI.zip)

**Comment by lshbluesky** [comment]
When I used the 2.3.0 version of RealtekRTL8111.kext, I had to manually set the Ethernet in Network in System Preferences to make the Internet work.

![스크린샷 2021-02-14 오후 4 06 55](https://user-images.githubusercontent.com/61459016/107870787-d0cfb380-6ede-11eb-8525-cd47235f67e0.png)

Alternatively, if you use the 2.2.0 version of RealtekRTL8111.kext, you will be able to connect to the Internet well without manual configuration.

**Comment by Invisiblearound** [comment]
I just want Your BIOS Config and Structure since i am unable to load your EFI
Basically I am using Opencore 0.6.6 
Their 2 Folder

1. com.apple.recovery.boot
2. EFI

But when i load ur EFI in boot its not showing and also importantly share BIOS Screenshot please

**Comment by lshbluesky** [comment]
Please add -v to boot-args and give me a specific description of the log picture and error.

In particular, the CFG Unlock option is usually hidden and cannot be changed in the BIOS settings.
Therefore, AppleXcpmCfgLock in Kernel-Quirks must be set to True in Config.plist.
Since I extracted the Setup_var of the CFG Lock related setting items from the BIOS update file and changed it directly from the GRUB Shell, I booted successfully even if AppleXcpmCfgLock is set to False. 

And the rest of my BIOS settings are as follows. 
- Hypet-Threading Technology : Enabled
- Intel Speed Shift Technology : Enabled
- Fast Boot : Disabled
- OS Type : Windows 8 / 10
- Secure Boot : Disabled
- Serial(COM) Port : Disabled
- Parallel Port : Disabled
- XHCI Hand-Off : Enabled
- Port 60/64 Emulation : Disabled
- SATA Mode : AHCI
- VT-d : Disabled
  - If DisableIoMapper is set to True, VT-d can be set to Enabled. 
- DVMT Pre-Allocated Memory : 128 MB

**Comment by Invisiblearound** [comment]
When i load ur EFI

![Boot](https://user-images.githubusercontent.com/62840373/107905393-8436b780-6f74-11eb-8921-28ddb7eab3dc.PNG)

In BioS
![01](https://user-images.githubusercontent.com/62840373/107905434-97e21e00-6f74-11eb-8a8f-5a9a729b5555.jpeg)
![02](https://user-images.githubusercontent.com/62840373/107905436-99134b00-6f74-11eb-9040-b4936e5334c3.jpeg)

It Shows only windows

**Comment by lshbluesky** [comment]
I'm not sure about that problem...
I can see the Mac OS boot items well.

Try using the Misc-Entries setting in Config.plist.
Or try setting UEFI - APFS - JumpstartHotPlug to False.

If it still doesn't work, I'm sorry, but I'm not sure.

**Comment by iyangsheng** [comment]
> When i load ur EFI
> 
> ![Boot](https://user-images.githubusercontent.com/62840373/107905393-8436b780-6f74-11eb-8921-28ddb7eab3dc.PNG)
> 
> In BioS
> ![01](https://user-images.githubusercontent.com/62840373/107905434-97e21e00-6f74-11eb-8a8f-5a9a729b5555.jpeg)
> ![02](https://user-images.githubusercontent.com/62840373/107905436-99134b00-6f74-11eb-9040-b4936e5334c3.jpeg)
> 
> It Shows only windows

Is it solved later
