### ISSUE TITLE
questions about your software

### ISSUE THREAD

**Issue by philbes** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#13]
Hi
I am a French living in Paris man 73 old and I built an hackintosh with clover on my PC : B250M-DS3H I5-7500. 
I want to build a Ventura one with opencore.
I found your contribution on Github.
I have some questions 👍 
1. About Bios settings
My Bios is version F9.
But, I cannot two parameters : Hyperthreading and Secure boot. Why ?
2. I dowloaded your software with 4 folders 👍 
- GitHub : only for infomation
- EFI : I should copy it on my EFI
- ACPI SSDT hot patches and OEM ACPI tables : what should I do with that folders ?
3. I have an I5 instead of I3 and an SSD Integral (M series NVMe) instead of a samsung : should I change something ?
Thanks a lot for your answer.
Philippe Besombes pbesombes49@gmail.com

**Comment by lshbluesky** [comment]
Hello. 🙂

1. Hyper-Threading Technology settings can be found in M.I.T - Advanced Frequency Settings - Advanced CPU Core Settings.
However, Intel 7th Gen KBL Core i5-7500 CPU does not support Hyper-Threading technology because it has 4 physical cores and 4 threads.
Hyper-Threading is a technology used in CPUs (i3, i7, etc.) with twice the number of threads as physical cores.
Secure Boot appears at the bottom only when CSM is set to Disabled in the BIOS tab.

2. The SSDT included in ACPI SSDT Hot Patches is already in the EFI - ACPI folder, I just decompiled it and uploaded the code to view on the GitHub website. The same goes for OEM ACPI Tables.

3. Since the iGPU is the same, there are no settings to change.
However, I recommend deleting the EDID value and connector patch in iGPU Properties because they are different for each user.
And, if your computer has a NVMe SSD, try adding [NVMeFix.kext](https://github.com/acidanthera/NVMeFix)

**Comment by philbes** [comment]
Thanks a lot for your quick answer.
I tried first with a ssd sata without doing anything for the igpu
properties.
The install starts working but stops after a few minutes with a black
screen.
I suppose it is because i am using hdmi
What can i do ?
Where are the igpu properties : in whatevergreen ?
Thanks
Philippe besombes
 ,



Le mer. 16 nov. 2022 à 03:40, lshbluesky ***@***.***> a
écrit :

**Comment by lshbluesky** [comment]
Replace it with the Config.plist attached below and try rebooting.
[Config.plist.zip](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/files/10020985/Config.plist.zip)

**Comment by lshbluesky** [comment]
The -igfxvesa boot arg was added as a temporary measure to eliminate the problem of not being able to boot to the iGPU.
Replace it with the Config.plist attached below and try rebooting.
[Config.plist.zip](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/files/10027346/Config.plist.zip)

If it still fails to boot, the reason why it does not boot is a cause other than iGPU.

**Comment by philbes** [comment]
Small detail, but I don't think it is important : I have a pic card for the
wifi.

Le jeu. 17 nov. 2022 à 08:06, philippe besombes ***@***.***> a
écrit :

**Comment by philbes** [comment]
[image: IMG_0287.jpg][image: IMG_0286.jpg]

Le jeu. 17 nov. 2022 à 03:54, lshbluesky ***@***.***> a
écrit :

**Comment by lshbluesky** [comment]
Photos are not visible.
Can you attach a photo directly from the GitHub website?
![스크린샷 2022-11-17 오후 7 20 36](https://user-images.githubusercontent.com/61459016/202420768-b7695567-c2a4-46ef-bb26-5363796227cb.png)

**Comment by philbes** [comment]
attached photos
![IMG_0286](https://user-images.githubusercontent.com/80748864/202422541-d7395708-c7a4-454a-a6fe-e4f7e157b487.jpg)
![IMG_0287](https://user-images.githubusercontent.com/80748864/202422555-bda9b445-dc95-4a5d-a6ca-ab38bc4f85c9.jpg)

**Comment by philbes** [comment]
![IMG_0286](https://user-images.githubusercontent.com/80748864/202422788-34d60426-eabc-4b71-923d-2295870be0d5.jpg)
![IMG_0287](https://user-images.githubusercontent.com/80748864/202422830-71efb4c0-0a42-4bff-994e-ab9d0785240a.jpg)

**Comment by philbes** [comment]
I hope it is better now

**Comment by philbes** [comment]
I did it


Le jeu. 17 nov. 2022 à 11:21, lshbluesky ***@***.***> a
écrit :

**Comment by lshbluesky** [comment]
Looking at the log of the picture you sent, do you have any external graphics(dGPU) on your computer?

**Comment by philbes** [comment]
No i don t have
Only the wifi card

Le jeu. 17 nov. 2022 à 12:35, lshbluesky ***@***.***> a
écrit :

**Comment by lshbluesky** [comment]
Can you tell me the model name of the Wi-Fi card chipset installed in your computer?
